import os
import json
import shutil
import subprocess
import sys

# Add backend to path to import app
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from covered.main import create_app, registry
from flask_rebar import SwaggerV3Generator


def main():
    print("Generating Swagger JSON...")
    app = create_app()
    with app.app_context():
        generator = SwaggerV3Generator()
        swagger = generator.generate(registry)

    # Write to temp file
    openapi_path = os.path.abspath("openapi.json")
    with open(openapi_path, "w") as f:
        json.dump(swagger, f, indent=2)

    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
    backend_package_dest = os.path.join(
        project_root, "backend/covered/autogenerated_client"
    )
    shared_client_dest = os.path.join(
        project_root, "apps/shared/src/autogenerated_client"
    )

    # Generate Python Client
    print("Generating Python Client...")
    python_temp = os.path.join(project_root, "temp_python_client")
    if os.path.exists(python_temp):
        shutil.rmtree(python_temp)

    cmd_python = [
        "npx",
        "-y",
        "@openapitools/openapi-generator-cli",
        "generate",
        "-i",
        openapi_path,
        "-g",
        "python",
        "-o",
        python_temp,
        "--additional-properties=packageName=covered.autogenerated_client",
    ]

    subprocess.run(cmd_python, check=True, cwd=project_root)

    # Move package
    source_client_pkg = os.path.join(python_temp, "covered/autogenerated_client")

    if os.path.exists(source_client_pkg):
        if os.path.exists(backend_package_dest):
            shutil.rmtree(backend_package_dest)

        shutil.copytree(source_client_pkg, backend_package_dest)
        print(f"Python client moved to {backend_package_dest}")
    else:
        print(f"Error: Could not find generated package at {source_client_pkg}")

    # Cleanup python temp
    if os.path.exists(python_temp):
        shutil.rmtree(python_temp)

    # Generate TypeScript Client
    print("Generating TypeScript Client...")
    if os.path.exists(shared_client_dest):
        shutil.rmtree(shared_client_dest)

    cmd_ts = [
        "npx",
        "-y",
        "@openapitools/openapi-generator-cli",
        "generate",
        "-i",
        openapi_path,
        "-g",
        "typescript-fetch",
        "-o",
        shared_client_dest,
        "--additional-properties=typescriptThreePlus=true,supportsES6=true",
    ]
    subprocess.run(cmd_ts, check=True, cwd=project_root)
    print(f"TypeScript client generated at {shared_client_dest}")

    # Cleanup openapi.json
    if os.path.exists(openapi_path):
        os.remove(openapi_path)
    print("Done.")


if __name__ == "__main__":
    main()
