/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaybackContentSchema
 */
export interface PlaybackContentSchema {
    /**
     * 
     * @type {string}
     * @memberof PlaybackContentSchema
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlaybackContentSchema
     */
    m4aFileUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PlaybackContentSchema
     */
    pageSnapshotUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PlaybackContentSchema
     */
    processedInputId: string;
    /**
     * 
     * @type {string}
     * @memberof PlaybackContentSchema
     */
    scriptJsonUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PlaybackContentSchema
     */
    thumbnailUrl?: string | null;
}

/**
 * Check if a given object implements the PlaybackContentSchema interface.
 */
export function instanceOfPlaybackContentSchema(value: object): value is PlaybackContentSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('m4aFileUrl' in value) || value['m4aFileUrl'] === undefined) return false;
    if (!('pageSnapshotUrl' in value) || value['pageSnapshotUrl'] === undefined) return false;
    if (!('processedInputId' in value) || value['processedInputId'] === undefined) return false;
    if (!('scriptJsonUrl' in value) || value['scriptJsonUrl'] === undefined) return false;
    return true;
}

export function PlaybackContentSchemaFromJSON(json: any): PlaybackContentSchema {
    return PlaybackContentSchemaFromJSONTyped(json, false);
}

export function PlaybackContentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaybackContentSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'm4aFileUrl': json['m4a_file_url'],
        'pageSnapshotUrl': json['page_snapshot_url'],
        'processedInputId': json['processed_input_id'],
        'scriptJsonUrl': json['script_json_url'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
    };
}

export function PlaybackContentSchemaToJSON(json: any): PlaybackContentSchema {
    return PlaybackContentSchemaToJSONTyped(json, false);
}

export function PlaybackContentSchemaToJSONTyped(value?: PlaybackContentSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'm4a_file_url': value['m4aFileUrl'],
        'page_snapshot_url': value['pageSnapshotUrl'],
        'processed_input_id': value['processedInputId'],
        'script_json_url': value['scriptJsonUrl'],
        'thumbnail_url': value['thumbnailUrl'],
    };
}

