/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessedInputSchema
 */
export interface ProcessedInputSchema {
    /**
     * 
     * @type {string}
     * @memberof ProcessedInputSchema
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedInputSchema
     */
    extractedLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessedInputSchema
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedInputSchema
     */
    sender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProcessedInputSchema
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessedInputSchema
     */
    title: string;
}

/**
 * Check if a given object implements the ProcessedInputSchema interface.
 */
export function instanceOfProcessedInputSchema(value: object): value is ProcessedInputSchema {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ProcessedInputSchemaFromJSON(json: any): ProcessedInputSchema {
    return ProcessedInputSchemaFromJSONTyped(json, false);
}

export function ProcessedInputSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessedInputSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'extractedLink': json['extracted_link'] == null ? undefined : json['extracted_link'],
        'id': json['id'],
        'sender': json['sender'] == null ? undefined : json['sender'],
        'timestamp': json['timestamp'],
        'title': json['title'],
    };
}

export function ProcessedInputSchemaToJSON(json: any): ProcessedInputSchema {
    return ProcessedInputSchemaToJSONTyped(json, false);
}

export function ProcessedInputSchemaToJSONTyped(value?: ProcessedInputSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'extracted_link': value['extractedLink'],
        'id': value['id'],
        'sender': value['sender'],
        'timestamp': value['timestamp'],
        'title': value['title'],
    };
}

