/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopicSchema } from './TopicSchema';
import {
    TopicSchemaFromJSON,
    TopicSchemaFromJSONTyped,
    TopicSchemaToJSON,
    TopicSchemaToJSONTyped,
} from './TopicSchema';

/**
 * 
 * @export
 * @interface TopicListSchema
 */
export interface TopicListSchema {
    /**
     * 
     * @type {Array<TopicSchema>}
     * @memberof TopicListSchema
     */
    topics: Array<TopicSchema>;
}

/**
 * Check if a given object implements the TopicListSchema interface.
 */
export function instanceOfTopicListSchema(value: object): value is TopicListSchema {
    if (!('topics' in value) || value['topics'] === undefined) return false;
    return true;
}

export function TopicListSchemaFromJSON(json: any): TopicListSchema {
    return TopicListSchemaFromJSONTyped(json, false);
}

export function TopicListSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicListSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(TopicSchemaFromJSON)),
    };
}

export function TopicListSchemaToJSON(json: any): TopicListSchema {
    return TopicListSchemaToJSONTyped(json, false);
}

export function TopicListSchemaToJSONTyped(value?: TopicListSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topics': ((value['topics'] as Array<any>).map(TopicSchemaToJSON)),
    };
}

