/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaybackContentSchema } from './PlaybackContentSchema';
import {
    PlaybackContentSchemaFromJSON,
    PlaybackContentSchemaFromJSONTyped,
    PlaybackContentSchemaToJSON,
    PlaybackContentSchemaToJSONTyped,
} from './PlaybackContentSchema';
import type { ProcessedInputSchema } from './ProcessedInputSchema';
import {
    ProcessedInputSchemaFromJSON,
    ProcessedInputSchemaFromJSONTyped,
    ProcessedInputSchemaToJSON,
    ProcessedInputSchemaToJSONTyped,
} from './ProcessedInputSchema';

/**
 * 
 * @export
 * @interface TopicSchema
 */
export interface TopicSchema {
    /**
     * 
     * @type {string}
     * @memberof TopicSchema
     */
    id: string;
    /**
     * 
     * @type {PlaybackContentSchema}
     * @memberof TopicSchema
     */
    playbackContent?: PlaybackContentSchema;
    /**
     * 
     * @type {ProcessedInputSchema}
     * @memberof TopicSchema
     */
    processedInput: ProcessedInputSchema;
    /**
     * 
     * @type {string}
     * @memberof TopicSchema
     */
    timestamp: string;
}

/**
 * Check if a given object implements the TopicSchema interface.
 */
export function instanceOfTopicSchema(value: object): value is TopicSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('processedInput' in value) || value['processedInput'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function TopicSchemaFromJSON(json: any): TopicSchema {
    return TopicSchemaFromJSONTyped(json, false);
}

export function TopicSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'playbackContent': json['playback_content'] == null ? undefined : PlaybackContentSchemaFromJSON(json['playback_content']),
        'processedInput': ProcessedInputSchemaFromJSON(json['processed_input']),
        'timestamp': json['timestamp'],
    };
}

export function TopicSchemaToJSON(json: any): TopicSchema {
    return TopicSchemaToJSONTyped(json, false);
}

export function TopicSchemaToJSONTyped(value?: TopicSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'playback_content': PlaybackContentSchemaToJSON(value['playbackContent']),
        'processed_input': ProcessedInputSchemaToJSON(value['processedInput']),
        'timestamp': value['timestamp'],
    };
}

