# coding: utf-8

"""
My API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from covered.autogenerated_client.models.playback_content_schema import (
    PlaybackContentSchema,
)
from covered.autogenerated_client.models.processed_input_schema import (
    ProcessedInputSchema,
)
from typing import Optional, Set
from typing_extensions import Self


class TopicSchema(BaseModel):
    """
    TopicSchema
    """  # noqa: E501

    id: StrictStr
    playback_content: Optional[PlaybackContentSchema] = None
    processed_input: ProcessedInputSchema
    timestamp: StrictStr
    __properties: ClassVar[List[str]] = [
        "id",
        "playback_content",
        "processed_input",
        "timestamp",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TopicSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of playback_content
        if self.playback_content:
            _dict["playback_content"] = self.playback_content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of processed_input
        if self.processed_input:
            _dict["processed_input"] = self.processed_input.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TopicSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "playback_content": PlaybackContentSchema.from_dict(
                    obj["playback_content"]
                )
                if obj.get("playback_content") is not None
                else None,
                "processed_input": ProcessedInputSchema.from_dict(
                    obj["processed_input"]
                )
                if obj.get("processed_input") is not None
                else None,
                "timestamp": obj.get("timestamp"),
            }
        )
        return _obj
