/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlaybackContentSchema,
  ProcessedInputSchema,
  TopicListSchema,
} from '../models/index';
import {
    PlaybackContentSchemaFromJSON,
    PlaybackContentSchemaToJSON,
    ProcessedInputSchemaFromJSON,
    ProcessedInputSchemaToJSON,
    TopicListSchemaFromJSON,
    TopicListSchemaToJSON,
} from '../models/index';

export interface CreatePlaybackContentRequest {
    playbackContentSchema: PlaybackContentSchema;
}

export interface CreateProcessedInputRequest {
    processedInputSchema: ProcessedInputSchema;
}

export interface GetProcessedInputRequest {
    inputId: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async createPlaybackContentRaw(requestParameters: CreatePlaybackContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaybackContentSchema>> {
        if (requestParameters['playbackContentSchema'] == null) {
            throw new runtime.RequiredError(
                'playbackContentSchema',
                'Required parameter "playbackContentSchema" was null or undefined when calling createPlaybackContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/playback-contents`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaybackContentSchemaToJSON(requestParameters['playbackContentSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaybackContentSchemaFromJSON(jsonValue));
    }

    /**
     */
    async createPlaybackContent(requestParameters: CreatePlaybackContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaybackContentSchema> {
        const response = await this.createPlaybackContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createProcessedInputRaw(requestParameters: CreateProcessedInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessedInputSchema>> {
        if (requestParameters['processedInputSchema'] == null) {
            throw new runtime.RequiredError(
                'processedInputSchema',
                'Required parameter "processedInputSchema" was null or undefined when calling createProcessedInput().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/processed-inputs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProcessedInputSchemaToJSON(requestParameters['processedInputSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessedInputSchemaFromJSON(jsonValue));
    }

    /**
     */
    async createProcessedInput(requestParameters: CreateProcessedInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessedInputSchema> {
        const response = await this.createProcessedInputRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProcessedInputRaw(requestParameters: GetProcessedInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessedInputSchema>> {
        if (requestParameters['inputId'] == null) {
            throw new runtime.RequiredError(
                'inputId',
                'Required parameter "inputId" was null or undefined when calling getProcessedInput().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/processed-inputs/{input_id}`;
        urlPath = urlPath.replace(`{${"input_id"}}`, encodeURIComponent(String(requestParameters['inputId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessedInputSchemaFromJSON(jsonValue));
    }

    /**
     */
    async getProcessedInput(requestParameters: GetProcessedInputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessedInputSchema> {
        const response = await this.getProcessedInputRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getTopicsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TopicListSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/topics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicListSchemaFromJSON(jsonValue));
    }

    /**
     */
    async getTopics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TopicListSchema> {
        const response = await this.getTopicsRaw(initOverrides);
        return await response.value();
    }

}
