import { Topic, ProcessedInput, PlaybackContent } from "../types";
import { DefaultApi, Configuration, TopicSchema, ProcessedInputSchema, PlaybackContentSchema } from "../autogenerated_client";

const mapProcessedInput = (schema: ProcessedInputSchema): ProcessedInput => {
    return {
        id: schema.id,
        timestamp: schema.timestamp,
        title: schema.title,
        content: schema.content,
        extracted_link: schema.extractedLink ?? undefined,
        sender: schema.sender ?? undefined,
    };
};

const mapPlaybackContent = (schema: PlaybackContentSchema): PlaybackContent => {
    return {
        id: schema.id,
        processed_input_id: schema.processedInputId,
        page_snapshot_url: schema.pageSnapshotUrl,
        thumbnail_url: schema.thumbnailUrl ?? undefined,
        script_json_url: schema.scriptJsonUrl,
        m4a_file_url: schema.m4aFileUrl,
    };
};

const mapTopic = (schema: TopicSchema): Topic => {
    return {
        id: schema.id,
        timestamp: schema.timestamp,
        processed_input: mapProcessedInput(schema.processedInput),
        playback_content: schema.playbackContent ? mapPlaybackContent(schema.playbackContent) : undefined,
    };
};

export const fetchTopics = async (baseUrl: string): Promise<Topic[]> => {
    const config = new Configuration({
        basePath: baseUrl || "",
    });
    const api = new DefaultApi(config);

    const response = await api.getTopics({ cache: 'no-store' });

    return response.topics.map(mapTopic);
};
